// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file/user.proto

package cn.mrcode.study.netty.test.protobuf;

public final class UserModule {
  private UserModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @return A list containing the favorite.
     */
    java.util.List<java.lang.String>
        getFavoriteList();
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @return The count of favorite.
     */
    int getFavoriteCount();
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @param index The index of the element to return.
     * @return The favorite at the given index.
     */
    java.lang.String getFavorite(int index);
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the favorite at the given index.
     */
    com.google.protobuf.ByteString
        getFavoriteBytes(int index);
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      userId_ = "";
      name_ = "";
      favorite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                favorite_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              favorite_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          favorite_ = favorite_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.mrcode.study.netty.test.protobuf.UserModule.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.mrcode.study.netty.test.protobuf.UserModule.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.mrcode.study.netty.test.protobuf.UserModule.User.class, cn.mrcode.study.netty.test.protobuf.UserModule.User.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAVORITE_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList favorite_;
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @return A list containing the favorite.
     */
    public com.google.protobuf.ProtocolStringList
        getFavoriteList() {
      return favorite_;
    }
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @return The count of favorite.
     */
    public int getFavoriteCount() {
      return favorite_.size();
    }
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @param index The index of the element to return.
     * @return The favorite at the given index.
     */
    public java.lang.String getFavorite(int index) {
      return favorite_.get(index);
    }
    /**
     * <pre>
     * 重复任意次 repeated，所以对应的就是 string[]
     * </pre>
     *
     * <code>repeated string favorite = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the favorite at the given index.
     */
    public com.google.protobuf.ByteString
        getFavoriteBytes(int index) {
      return favorite_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      for (int i = 0; i < favorite_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, favorite_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < favorite_.size(); i++) {
          dataSize += computeStringSizeNoTag(favorite_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFavoriteList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.mrcode.study.netty.test.protobuf.UserModule.User)) {
        return super.equals(obj);
      }
      cn.mrcode.study.netty.test.protobuf.UserModule.User other = (cn.mrcode.study.netty.test.protobuf.UserModule.User) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getFavoriteList()
          .equals(other.getFavoriteList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getFavoriteCount() > 0) {
        hash = (37 * hash) + FAVORITE_FIELD_NUMBER;
        hash = (53 * hash) + getFavoriteList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.mrcode.study.netty.test.protobuf.UserModule.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.mrcode.study.netty.test.protobuf.UserModule.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        cn.mrcode.study.netty.test.protobuf.UserModule.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.mrcode.study.netty.test.protobuf.UserModule.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.mrcode.study.netty.test.protobuf.UserModule.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.mrcode.study.netty.test.protobuf.UserModule.User.class, cn.mrcode.study.netty.test.protobuf.UserModule.User.Builder.class);
      }

      // Construct using cn.mrcode.study.netty.test.protobuf.UserModule.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        age_ = 0;

        name_ = "";

        favorite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.mrcode.study.netty.test.protobuf.UserModule.internal_static_User_descriptor;
      }

      @java.lang.Override
      public cn.mrcode.study.netty.test.protobuf.UserModule.User getDefaultInstanceForType() {
        return cn.mrcode.study.netty.test.protobuf.UserModule.User.getDefaultInstance();
      }

      @java.lang.Override
      public cn.mrcode.study.netty.test.protobuf.UserModule.User build() {
        cn.mrcode.study.netty.test.protobuf.UserModule.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.mrcode.study.netty.test.protobuf.UserModule.User buildPartial() {
        cn.mrcode.study.netty.test.protobuf.UserModule.User result = new cn.mrcode.study.netty.test.protobuf.UserModule.User(this);
        int from_bitField0_ = bitField0_;
        result.userId_ = userId_;
        result.age_ = age_;
        result.name_ = name_;
        if (((bitField0_ & 0x00000001) != 0)) {
          favorite_ = favorite_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.favorite_ = favorite_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.mrcode.study.netty.test.protobuf.UserModule.User) {
          return mergeFrom((cn.mrcode.study.netty.test.protobuf.UserModule.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.mrcode.study.netty.test.protobuf.UserModule.User other) {
        if (other == cn.mrcode.study.netty.test.protobuf.UserModule.User.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.favorite_.isEmpty()) {
          if (favorite_.isEmpty()) {
            favorite_ = other.favorite_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFavoriteIsMutable();
            favorite_.addAll(other.favorite_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.mrcode.study.netty.test.protobuf.UserModule.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.mrcode.study.netty.test.protobuf.UserModule.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList favorite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFavoriteIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          favorite_ = new com.google.protobuf.LazyStringArrayList(favorite_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @return A list containing the favorite.
       */
      public com.google.protobuf.ProtocolStringList
          getFavoriteList() {
        return favorite_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @return The count of favorite.
       */
      public int getFavoriteCount() {
        return favorite_.size();
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @param index The index of the element to return.
       * @return The favorite at the given index.
       */
      public java.lang.String getFavorite(int index) {
        return favorite_.get(index);
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the favorite at the given index.
       */
      public com.google.protobuf.ByteString
          getFavoriteBytes(int index) {
        return favorite_.getByteString(index);
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @param index The index to set the value at.
       * @param value The favorite to set.
       * @return This builder for chaining.
       */
      public Builder setFavorite(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFavoriteIsMutable();
        favorite_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @param value The favorite to add.
       * @return This builder for chaining.
       */
      public Builder addFavorite(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFavoriteIsMutable();
        favorite_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @param values The favorite to add.
       * @return This builder for chaining.
       */
      public Builder addAllFavorite(
          java.lang.Iterable<java.lang.String> values) {
        ensureFavoriteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, favorite_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFavorite() {
        favorite_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复任意次 repeated，所以对应的就是 string[]
       * </pre>
       *
       * <code>repeated string favorite = 4;</code>
       * @param value The bytes of the favorite to add.
       * @return This builder for chaining.
       */
      public Builder addFavoriteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFavoriteIsMutable();
        favorite_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final cn.mrcode.study.netty.test.protobuf.UserModule.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.mrcode.study.netty.test.protobuf.UserModule.User();
    }

    public static cn.mrcode.study.netty.test.protobuf.UserModule.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.mrcode.study.netty.test.protobuf.UserModule.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017file/user.proto\"C\n\004User\022\016\n\006userId\030\001 \001(" +
      "\t\022\013\n\003age\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\020\n\010favorite" +
      "\030\004 \003(\tB1\n#cn.mrcode.study.netty.test.pro" +
      "tobufB\nUserModuleb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "UserId", "Age", "Name", "Favorite", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
